### ISSUE TITLE
x_expanded = x[:,self.neighbors_ix_mat,:] Wrong？？

### ISSUE THREAD

**Issue by JJJTF** [hechtlinger/graph_cnn#5]
WARNING:tensorflow:From F:\python3.7\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "F:\python3.7\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 458, in _apply_op_helper
    raise TypeError()  # All types should match.
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Graph_cnn/graph_cnn-master/code/MNIST_grid_graph.py", line 59, in <module>
    input_shape=(X_train.shape[1],1,)))
  File "F:\python3.7\lib\site-packages\keras\engine\sequential.py", line 165, in add
    layer(x)
  File "F:\python3.7\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\Graph_cnn\graph_cnn-master\code\graph_convolution.py", line 132, in call
    x_expanded = x[:,self.neighbors_ix_mat,:]
  File "F:\python3.7\lib\site-packages\tensorflow\python\ops\array_ops.py", line 629, in _slice_helper
    packed_begin, packed_end, packed_strides = (stack(begin), stack(end),
  File "F:\python3.7\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "F:\python3.7\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1005, in stack
    return gen_array_ops.pack(values, axis=axis, name=name)
  File "F:\python3.7\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6426, in pack
    "Pack", values=values, axis=axis, name=name)
  File "F:\python3.7\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 483, in _apply_op_helper
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, int64, int32] that don't all match.

Thanks to the author for answering my last question!
The above error occurred when I ran the source code.
and my backend is thesorflow  .

**Comment by hechtlinger** [comment]
It's only implemented for theano.
Back then tf didn't have straightforward implementation of tensordot. I now
see they implemented it.

I'll try to see if it can be updated. Until then either use theano (I
know...) or have a look at line 130 in the graph convolution layer and see
if you can make it work for the tf backend.

**Comment by JJJTF** [comment]
But the error is in   "x_expanded = x[:,self.neighbors_ix_mat,:]"
and  TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, int64, int32] that don't all match.
Is this caused by the  tf backend ?
Thanks for your answer!

**Comment by hechtlinger** [comment]
This error seems to be happening because the data type is not consistent.
Verify the data type is the same. It seems like the X is int32 while the
neighbor matrix is int64.

Regardless it shouldn't work with tensorflow.

**Comment by JJJTF** [comment]
Thank you!  
I will try it!
